s3_bucket_name                    = "tf1-smresume-s3"
cf_oac_name                       = "tf1-smresume-oac"
acm_ssl_arn                       = "arn:aws:acm:us-east-1:841037355733:certificate/d14da19d-85be-43ab-b88b-f365433dd687"
subdomain                         = "resumeqa"
domain                            = "gensosekai.com"
smresume_oac_id                   = "tf1-smresume-oac-id"
